#!/bin/bash

if [ -f /etc/zramswap.conf ]; then
  source /etc/zramswap.conf
fi

start() {
  if [ -n "$ZRAM_DISK_SIZE" ]; then
    MEM="$ZRAM_DISK_SIZE"
  else
    if [ ! "$ZRAM_SIZE_PERCENT" ]; then
      ZRAM_SIZE_PERCENT=20
    fi
    (( MEM_TOTAL= `cat /proc/meminfo | grep MemTotal | awk '{print $2}'` * 1024 ))
    (( MEM= MEM_TOTAL * $ZRAM_SIZE_PERCENT / 100 ))
  fi

  modprobe zram
  if [ -n "$ZRAM_COMPRESSION_ALGO" ]; then
    echo "$ZRAM_COMPRESSION_ALGO" > /sys/block/zram0/comp_algorithm
  fi

  if [ -n "$ZRAM_WRITEBACK_DEV" ]; then
    echo "$ZRAM_WRITEBACK_DEV" > /sys/block/zram0/backing_dev
  fi

  echo $MEM > /sys/block/zram0/disksize

  if [ -n "$ZRAM_MEM_LIMIT" ]; then
    echo "$ZRAM_MEM_LIMIT" > /sys/block/zram0/mem_limit
  fi

  mkswap /dev/zram0 -L zram0
  swapon -p 100 /dev/zram0
}

stop() {
  swapoff /dev/zram0
  rmmod zram
}

case $1 in
  start|stop) "$1" ;;
esac
